---
title: "Untitled"
author: "Annon. Reviewer"
date: "2024-03-21"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(MyFunctions)
library(tidyverse)
library(here)
library(sf)
```


# Load data

```{r}

# Get taxon list
taxon_list <- my_data("sau_species")

# Missing Species by Yulia
missing_sp <- read.csv("~/Library/CloudStorage/OneDrive-UBC/Data/dbem/missing_runs_yulia/missing_sp.csv") %>% 
  group_by(taxon_key = taxonkey) %>% 
  tally() %>% 
  select(-n) %>% 
  left_join(taxon_list)


# Get list of available distributions
complete_distributions <- list.files("~/Library/CloudStorage/OneDrive-UBC/Data/Species/Distributions/",full.names = T)
distributions <- list.files("~/Library/CloudStorage/OneDrive-UBC/Data/Species/Distributions/")
distributions <- str_sub(distributions,2,7)

# Available distributions 
distributions_df <- as.data.frame(distributions) %>% 
  slice(-1:-2) %>% 
  rename(taxon_key = distributions) %>% 
  mutate(distributions = 1)


```

## Cross ref. missing distributions with availlable data

```{r}

spp_to_run <- missing_sp %>% 
  mutate(
    will_run = ifelse(taxon_key %in% distributions,"Yes","No")
  )

write_csv(spp_to_run,"~/Library/CloudStorage/OneDrive-UBC/Data/dbem/missing_runs_yulia/spp_to_run.csv")

```


## Test distributions

```{r}

missing_sp_path <- distributions_df %>% 
  group_by(taxon_key) %>% 
  tally() %>% 
  mutate(read_missing = paste0("~/Library/CloudStorage/OneDrive-UBC/Data/Species/Distributions/S",taxon_key,".csv"))

dbem_coords <- MyFunctions::my_data("dbem_coords")

i = 5

# for(i in 872:nrow(missing_sp_path)){
  
  read_path <- missing_sp_path$read_missing[i]
  print(str_sub(read_path,65,70))
  
  
  if(file.exists(read_path)){
    
    spp_df <- read.csv(read_path,header = F) %>% 
      bind_cols(dbem_coords) %>% 
      filter(V1 > 0)
    
    glob_map <- spp_df %>%
      ggplot() +
      geom_tile(
        aes(
          x = lon,
          y = lat,
          fill = V1,
          color = V1
        )
      ) +
      MyFunctions::my_land_map() +
      scale_fill_viridis_b("Distribution") +
      scale_color_viridis_b("Distribution") +
      ggtitle(paste0("Distribution of ",str_sub(read_path,65,70)," ",taxon_list %>% filter(taxon_key %in% str_sub(read_path,65,70)) %>% pull(common_name))) +
      theme_classic() +
      theme(legend.position = "")
    
    zoom_map <- spp_df %>% 
      ggplot() +
      geom_tile(
        aes(
          x = lon,
          y = lat,
          fill = V1,
          color = V1
        )
      ) +
      MyFunctions::my_land_map() +
      scale_fill_viridis_b("Distribution") +
      scale_color_viridis_b("Distribution") +
      # ggtitle(paste0("Distribution of ",str_sub(read_path,65,70)," ",taxon_list %>% filter(taxon_key %in% str_sub(read_path,65,70)) %>% pull(common_name))) +
      coord_sf(
        x = c(min(spp_df$lon-5),max(spp_df$lon+5)),
        y = c(min(spp_df$lat-5),max(spp_df$lat+5))
      ) +
      theme_classic() +
      theme(legend.position = c(4,1))
    
    
    pp <- gridExtra::grid.arrange(glob_map,zoom_map, ncol =1)
  
    
      ggsave(filename = paste0("~/Library/CloudStorage/OneDrive-UBC/Data/Species/Distributions_maps/",missing_sp_path$taxon_key[i],".png"),
             plot = pp,
             width = 10,
             height = 10)
    
  }else{
    
    print(paste("no distribution of ",str_sub(read_path,65,70)))
  }
  
# }

```

# Prepare data for runs

## Create species files

```{r}

# Create species list... just do it manually
dbem_spp_list <- spp_to_run %>% 
  filter(will_run == "Yes") %>% 
  select(taxon_key)
    

# Manually making lists of 27 species each. NOTE 27 not 40!

# MisSppList10

dbem_spp_list_10 <- dbem_spp_list %>% 
  slice(1:27)

    name <- paste0(here(),"/data/species/MisSppList10.txt")
    write.table(dbem_spp_list_10, file=name, sep="\t", col.names = F, row.names = F)
  
# MisSppList11

dbem_spp_list_11 <- dbem_spp_list %>% 
  slice(27:53)

    name <- paste0(here(),"/data/species/MisSppList11.txt")
    write.table(dbem_spp_list_11, file=name, sep="\t", col.names = F, row.names = F)
    
```

